version: "3"
services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      # app_net:
      #   ipv4_address: 172.16.238.10
      - app_net

  java:
    image: openjdk:8
    container_name: java
    volumes:
      - ./java:/opt/app
    ports:
      - 8080:8080
    # links:
    #   - mysql
    networks:
      # app_net:
      #   ipv4_address: 172.16.238.11
      - app_net
    command: java -jar /opt/app/api.war

  nginx:
    # image: nginx:alpine
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/etc:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
    # links:
    #   - mysql:default
    networks:
      # app_net:
      #   ipv4_address: 172.16.238.12
      - app_net

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
        - subnet: 2001:3984:3989::/64
